default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check .
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]

      - id: mypy-core
        name: mypy-core
        entry: mypy
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]

      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        stages: [pre-push]
