"""Spiro-Logic: deterministic CPET expert logic (Wasserman, ESC 2022, Guazzi).

Clinical design goals
---------------------
- Deterministic, testable, reproducible (no LLM dependencies)
- Immediate plausibility checks and pattern recognition
- Live education text for each module

This module intentionally avoids mutating UI values.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple


def _sf(x: Any) -> Optional[float]:
    try:
        if x is None or x == "":
            return None
        return float(x)
    except Exception:
        return None


def _s(x: Any) -> str:
    return "" if x is None else str(x).strip()


# Treat "0" as "missing" for physiologic variables that cannot be 0 in a real CPET.
# This avoids misleading autogenerated text when fields are left empty but default to 0 in some environments.
_ZERO_IS_MISSING_KEYS = {
    "cpet_rer_peak",
    "cpet_hr_peak_bpm",
    "cpet_hr_pct_pred",
    "cpet_peak_vo2_ml_kg_min",
    "cpet_peak_vo2_pct_pred",
    "cpet_peak_o2_pulse_ml",
    "cpet_o2_pulse_slope",
    "cpet_vo2_wr_slope_ml_min_w",
    "cpet_bp_sys_rest",
    "cpet_bp_dia_rest",
    "cpet_bp_sys_peak",
    "cpet_bp_dia_peak",
    "cpet_ve_vco2_slope",
    "cpet_petco2_rest_mmhg",
    "cpet_petco2_peak_mmhg",
    "cpet_petco2_vt1_mmhg",
    "cpet_breathing_reserve_pct",
    "cpet_ve_vco2_vt1",
    "cpet_spo2_rest_pct",
    "cpet_spo2_peak_pct",
    "cpet_spo2_nadir_pct",
    "cpet_o2_supp_l_min",
    "cpet_ve_peak_l_min",
    "cpet_mvv_l_min",
    "cpet_vo2_vt1_ml_kg_min",
    "cpet_vo2_vt2_ml_kg_min",
    "cpet_vo2_vt1_ml_min",
    "cpet_vo2_vt2_ml_min",
}


def _sfk(ui: Dict[str, Any], key: str) -> Optional[float]:
    """Safe-float reader for UI dict with sensible missing handling."""
    v = _sf(ui.get(key))
    if v is None:
        return None
    if v == 0 and key in _ZERO_IS_MISSING_KEYS:
        return None
    return v

@dataclass
class ModuleResult:
    title: str
    status: str
    severity: str  # info, warn, bad
    feedback: str
    teaching: str
    followups: List[str]
    flags: Dict[str, Any]


@dataclass
class SpiroLogicResult:
    module0: ModuleResult
    module1: ModuleResult
    module2: ModuleResult
    module3: ModuleResult
    module4: ModuleResult
    module5_mech: ModuleResult
    module6_gas: ModuleResult
    module7_safety: ModuleResult
    module9: ModuleResult
    module_final: ModuleResult
    overall_summary: str
    headline: str
    clinical_summary: str
    report_text: str
    derived: Dict[str, Any]


def _badge(sev: str) -> str:
    sev = (sev or "info").lower()
    if sev == "bad":
        return "🔴"
    if sev == "warn":
        return "🟠"
    return "🟢"


def _fmt(x: Optional[float], nd: int = 1) -> str:
    if x is None:
        return ""
    try:
        if nd == 0:
            return f"{x:.0f}"
        return f"{x:.{nd}f}"
    except Exception:
        return ""


def analyze_module_1(ui: Dict[str, Any]) -> ModuleResult:
    rer = _sfk(ui, "cpet_rer_peak")
    hr_peak = _sfk(ui, "cpet_hr_peak_bpm")
    hr_pct = _sfk(ui, "cpet_hr_pct_pred")
    hypervent = bool(ui.get("cpet_hyperventilation"))
    beta_blocker = bool(ui.get("cpet_beta_blocker"))
    sinus_node = bool(ui.get("cpet_sinus_node_disorder"))

    followups: List[str] = []
    flags: Dict[str, Any] = {}

    # Effort
    effort_ok: Optional[bool] = None
    effort_txt = ""
    if rer is not None:
        if rer >= 1.10:
            effort_ok = True
            effort_txt = "RER spricht für maximale metabolische Ausbelastung."
        elif rer >= 1.05:
            effort_ok = True
            effort_txt = "RER spricht für hohe Ausbelastung, maximal wahrscheinlich."
        else:
            effort_ok = False
            effort_txt = "RER spricht eher gegen maximale Ausbelastung."
    else:
        effort_txt = "RER nicht angegeben, Ausbelastung nicht sicher beurteilbar."

    # Chronotropy
    chronotropic_flag = False
    chronotropic_txt = ""
    if (rer is not None and rer >= 1.10) and (hr_pct is not None and hr_pct < 85):
        chronotropic_flag = True
        chronotropic_txt = "Maximale metabolische Ausbelastung bei inadäquater Herzfrequenzsteigerung. Verdacht auf chronotrope Inkompetenz."
        followups.append("Bitte prüfen: Betablocker oder andere Frequenz bremsende Medikation?")
        followups.append("Bitte prüfen: Hinweise auf Sinusknotenerkrankung oder Schrittmacherabhängigkeit?")
    elif (hr_pct is not None and hr_pct < 85) and (rer is not None and rer >= 1.05):
        chronotropic_txt = "Herzfrequenzanstieg erscheint niedrig im Verhältnis zur Anstrengung. Chronotrope Limitation möglich."

    if hypervent and (rer is not None and rer >= 1.10):
        followups.append("Hinweis: mögliche Hyperventilation kann RER falsch hoch erscheinen lassen. Bitte klinische Situation bewerten.")

    flags["cpet_effort_ok_local"] = effort_ok
    flags["cpet_chronotropic_suspected"] = chronotropic_flag

    # Compose feedback
    parts: List[str] = []
    if rer is not None:
        parts.append(f"RER Peak { _fmt(rer,2) }.")
    if hr_peak is not None:
        parts.append(f"HF Peak { _fmt(hr_peak,0) } 1/min.")
    if hr_pct is not None:
        parts.append(f"HF { _fmt(hr_pct,0) } % Soll.")
    if parts:
        parts.append(effort_txt)
    if chronotropic_txt:
        parts.append(chronotropic_txt)
    if beta_blocker:
        parts.append("Betablocker dokumentiert, Frequenzantwort kann medikamentös limitiert sein.")
    if sinus_node:
        parts.append("Sinusknotenstörung dokumentiert, chronotrope Limitation ist plausibel.")

    feedback = " ".join([p for p in parts if p])

    teaching = (
        "RER ist das Verhältnis von VCO2 zu VO2. Im aeroben Stoffwechsel liegt der RER typischerweise zwischen 0.7 und 1.0. "
        "Bei Überschreiten der anaeroben Schwelle entsteht Laktat. Protonen werden über Bikarbonat gepuffert, dabei entsteht zusätzliches CO2, "
        "das abgeatmet wird. Ein RER über 1.10 ist daher ein starker Hinweis auf maximale Ausbelastung. "
        "Fallstrick: Angst oder Hyperventilation kann CO2 auswaschen und den RER erhöhen, ohne echte metabolische Maximalleistung. "
        "Wenn bei hoher Ausbelastung die Herzfrequenz deutlich unter dem Soll bleibt, ist chronotrope Inkompetenz wahrscheinlich und sollte gezielt abgefragt werden."
    )

    if chronotropic_flag:
        severity = "warn"
        status = "chronotropic_incompetence"
    else:
        severity = "info" if (effort_ok is None or effort_ok) else "warn"
        status = "ok" if (effort_ok is None or effort_ok) else "submaximal_effort"

    return ModuleResult(
        title="Modul 1: Antrieb (Metabolik und Chronotropie)",
        status=status,
        severity=severity,
        feedback=feedback or "",
        teaching=teaching,
        followups=followups,
        flags=flags,
    )


def analyze_module_0_quality(ui: Dict[str, Any]) -> ModuleResult:
    """Quality and validity of the CPET.

    This module focuses on *interpretation safety*: without a valid test,
    downstream pattern recognition may be misleading.
    """

    rer = _sfk(ui, "cpet_rer_peak")
    hr_pct = _sfk(ui, "cpet_hr_pct_pred")
    borg_rpe = _sf(ui.get("cpet_borg_rpe"))
    borg_dysp = _sf(ui.get("cpet_borg_dyspnea"))
    borg_leg = _sf(ui.get("cpet_borg_leg"))
    stop_reason = _s(ui.get("cpet_stop_reason"))
    stop_reason_text = _s(ui.get("cpet_stop_reason_text"))
    hypervent = bool(ui.get("cpet_hyperventilation"))

    followups: List[str] = []
    flags: Dict[str, Any] = {}

    # Maximality heuristic
    effort: str = "unklar"
    effort_ok: Optional[bool] = None

    rer_ok = (rer is not None and rer >= 1.10)
    rer_high = (rer is not None and rer >= 1.05)
    borg_ok = (borg_rpe is not None and borg_rpe >= 9)

    if rer_ok or borg_ok:
        effort = "maximal wahrscheinlich"
        effort_ok = True
    elif rer_high:
        effort = "hoch, maximal möglich"
        effort_ok = True
    elif rer is not None or borg_rpe is not None:
        effort = "eher submaximal"
        effort_ok = False

    # Safety stop reasons: allow a valid interpretation even if not "maximal"
    safety_stop = stop_reason.lower() in {
        "angina/ischämie",
        "schwindel/präsynkope/synkope",
        "arrhythmie",
        "hypotonie",
        "desaturation",
    }

    if hypervent and rer_ok:
        followups.append("Achtung: Hyperventilation kann den RER erhöhen (Pseudo Max). Bitte Maskensitz/Angst/Atmung bewerten.")

    if effort_ok is False and not safety_stop:
        followups.append("Bei submaximaler Ausbelastung ist die Interpretation (insb. VO2peak) limitiert. Bitte Abbruchgrund dokumentieren.")

    parts: List[str] = []
    if stop_reason:
        parts.append(f"Testende: {stop_reason}.")
    if stop_reason_text:
        parts.append(f"Details: {stop_reason_text}.")
    if rer is not None:
        parts.append(f"RER Peak {_fmt(rer,2)}.")
    if hr_pct is not None:
        parts.append(f"HF Peak {_fmt(hr_pct,0)} % Soll.")
    if borg_rpe is not None:
        parts.append(f"Borg RPE {_fmt(borg_rpe,0)}/10.")
    if borg_dysp is not None:
        parts.append(f"Borg Dyspnoe {_fmt(borg_dysp,0)}/10.")
    if borg_leg is not None:
        parts.append(f"Borg Beine {_fmt(borg_leg,0)}/10.")
    if effort != "unklar":
        parts.append(f"Ausbelastung: {effort}.")
    if safety_stop:
        parts.append("Hinweis: Abbruch aus Sicherheitsgründen kann die Maximalitätskriterien relativieren. Die Musterinterpretation bleibt möglich, muss aber im Kontext erfolgen.")

    flags["cpet_test_effort_ok_local"] = effort_ok
    flags["cpet_stop_safety_local"] = safety_stop
    flags["cpet_test_quality_status"] = effort

    if effort_ok is False and not safety_stop:
        severity = "warn"
        status = "submaximal"
    else:
        severity = "info"
        status = "ok" if effort_ok is not False else "unclear"

    teaching = (
        "Die Aussagekraft einer CPET hängt entscheidend von der Testqualität ab. "
        "Maximalitätskriterien sind v.a. ein RER ≥ 1.10 (chemischer Beweis einer metabolischen Ausbelastung) und/oder eine sehr hohe subjektive Anstrengung (Borg RPE). "
        "Ein RER kann bei Hyperventilation künstlich erhöht sein. Umgekehrt kann ein Test aus Sicherheitsgründen (Angina, Arrhythmie, Hypotonie, Desaturation) beendet werden, "
        "bevor klassische Maximalitätskriterien erreicht sind. Dann ist die Interpretation weiterhin möglich, muss aber explizit als sicherheitslimitiert dokumentiert werden."
    )

    return ModuleResult(
        title="Modul 0: Testqualität und Validität",
        status=status,
        severity=severity,
        feedback=" ".join([p for p in parts if p]).strip(),
        teaching=teaching,
        followups=followups,
        flags=flags,
    )


def analyze_module_5_mech(ui: Dict[str, Any]) -> ModuleResult:
    """Mechanical ventilatory limitation proof (VE/MVV), optional but guideline-aligned."""

    ve_peak = _sfk(ui, "cpet_ve_peak_l_min")
    mvv = _sfk(ui, "cpet_mvv_l_min")
    mvv_src = _s(ui.get("cpet_mvv_source"))
    br_pct = _sfk(ui, "cpet_breathing_reserve_pct")
    flow_lim = _s(ui.get("cpet_9panel_flowvol_limit")).lower()

    followups: List[str] = []
    flags: Dict[str, Any] = {}

    ve_mvv_ratio: Optional[float] = None
    br_calc: Optional[float] = None

    if ve_peak is not None and mvv is not None and mvv > 0:
        ve_mvv_ratio = ve_peak / mvv
        br_calc = (1.0 - ve_mvv_ratio) * 100.0

    mech_limited = False
    parts: List[str] = []

    if ve_peak is not None:
        parts.append(f"V'E Peak {_fmt(ve_peak,0)} L/min.")
    if mvv is not None:
        src_txt = f" ({mvv_src})" if mvv_src else ""
        parts.append(f"MVV {_fmt(mvv,0)} L/min{src_txt}.")
    if ve_mvv_ratio is not None:
        parts.append(f"V'E/MVV {_fmt(ve_mvv_ratio,2)}.")
    if br_pct is not None:
        parts.append(f"Atemreserve (eingetragen) {_fmt(br_pct,0)} %.")
    if br_calc is not None:
        parts.append(f"Atemreserve (berechnet) {_fmt(br_calc,0)} %.")

    # Decision: prefer VE/MVV if available, else use breathing reserve
    br_use = br_calc if br_calc is not None else br_pct
    if br_use is not None:
        if br_use < 15:
            mech_limited = True
            parts.append("Atemreserve ist niedrig. Das spricht für ventilatorische Limitation.")
        elif br_use >= 20:
            parts.append("Atemreserve ist erhalten. Ventilatorische Limitation ist unwahrscheinlich.")

    if flow_lim == "ja":
        parts.append("Flow Volume Loop Einschränkung unterstützt eine mechanische Limitation.")
        mech_limited = True if br_use is None else mech_limited

    if ve_peak is None or mvv is None:
        followups.append("Optional: V'E Peak und MVV dokumentieren (oder MVV schätzen), um mechanische Limitation objektiv über V'E/MVV zu belegen.")

    flags["cpet_mechanical_limited_local"] = mech_limited
    flags["cpet_ve_mvv_ratio_local"] = ve_mvv_ratio
    flags["cpet_breathing_reserve_calc_local"] = br_calc

    if mech_limited:
        severity = "warn"
        status = "mechanical_limit"
    else:
        severity = "info"
        status = "no_mechanical_limit" if br_use is not None else "missing"

    teaching = (
        "Eine ventilatorische Limitation sollte möglichst objektiv belegt werden. Der klassische Ansatz ist V'E/MVV: "
        "wenn die Spitzenventilation (V'E Peak) nahe an der maximalen willkürlichen Ventilation (MVV) liegt, bleibt kaum Atemreserve. "
        "Eine Atemreserve < 15 % oder ein V'E/MVV ≥ 0.85 spricht für mechanische Limitation. "
        "Erhaltene Atemreserve spricht gegen eine primär mechanische Lungenlimitation und lenkt die Interpretation stärker in Richtung Kreislauf oder Gefäße."
    )

    return ModuleResult(
        title="Modul 5: Mechanik (V'E/MVV und Atemreserve)",
        status=status,
        severity=severity,
        feedback=" ".join([p for p in parts if p]).strip(),
        teaching=teaching,
        followups=followups,
        flags=flags,
    )


def analyze_module_6_gas(ui: Dict[str, Any]) -> ModuleResult:
    """Gas exchange red flags (SpO2) and oxygen support context."""

    spo2_rest = _sfk(ui, "cpet_spo2_rest_pct")
    spo2_peak = _sfk(ui, "cpet_spo2_peak_pct")
    spo2_nadir = _sfk(ui, "cpet_spo2_nadir_pct")
    o2_l_min = _sfk(ui, "cpet_o2_supp_l_min")

    followups: List[str] = []
    flags: Dict[str, Any] = {}

    # Use nadir if present, else peak
    spo2_min = spo2_nadir if spo2_nadir is not None else spo2_peak
    drop = None
    if spo2_rest is not None and spo2_min is not None:
        drop = spo2_rest - spo2_min

    significant_desat = False
    if spo2_min is not None and spo2_min < 88:
        significant_desat = True
    if drop is not None and drop >= 4:
        significant_desat = True

    parts: List[str] = []
    if spo2_rest is not None:
        parts.append(f"SpO2 Ruhe {_fmt(spo2_rest,0)} %.")
    if spo2_peak is not None:
        parts.append(f"SpO2 Peak {_fmt(spo2_peak,0)} %.")
    if spo2_nadir is not None:
        parts.append(f"SpO2 Nadir {_fmt(spo2_nadir,0)} %.")
    if drop is not None:
        parts.append(f"ΔSpO2 {_fmt(drop,0)} %.")
    if o2_l_min is not None and o2_l_min > 0:
        parts.append(f"O2 Unterstützung {_fmt(o2_l_min,1)} L/min während CPET.")

    if significant_desat:
        parts.append("Desaturation ist klinisch relevant. Differenzialdiagnostisch kommen Diffusionsstörung, V/Q Mismatch, Shunt oder pulmonal vaskuläre Einschränkung in Betracht.")
        followups.append("Bitte Kontext dokumentieren (O2 Gabe, ILD/COPD, Shunt, pulmonal vaskuläre Erkrankung).")

    flags["cpet_desaturation_local"] = significant_desat
    flags["cpet_spo2_drop_local"] = drop

    severity = "warn" if significant_desat else "info"
    status = "desaturation" if significant_desat else ("ok" if spo2_min is not None else "missing")

    teaching = (
        "SpO2 unter Belastung liefert wichtige Hinweise auf den Gasaustausch. Eine relevante Desaturation (z.B. SpO2 < 88 % oder Abfall ≥ 4 %) "
        "spricht gegen reine Deconditioning Muster und sollte differenzialdiagnostisch eingeordnet werden: Diffusionsstörung (ILD), V/Q Mismatch (Embolie/PH), "
        "Shunt oder schwere ventilatorische Einschränkung. "
        "Die Dokumentation einer O2 Unterstützung ist essenziell, um Verläufe vergleichbar zu machen."
    )

    return ModuleResult(
        title="Modul 6: Gasaustausch (SpO2 und O2 Unterstützung)",
        status=status,
        severity=severity,
        feedback=" ".join([p for p in parts if p]).strip(),
        teaching=teaching,
        followups=followups,
        flags=flags,
    )


def analyze_module_7_safety(ui: Dict[str, Any]) -> ModuleResult:
    """Safety block: blood pressure response, arrhythmia, ischemia, symptoms."""

    bp_sys_rest = _sfk(ui, "cpet_bp_sys_rest")
    bp_dia_rest = _sfk(ui, "cpet_bp_dia_rest")
    bp_sys_peak = _sfk(ui, "cpet_bp_sys_peak")
    bp_dia_peak = _sfk(ui, "cpet_bp_dia_peak")

    angina = bool(ui.get("cpet_angina"))
    dizziness = bool(ui.get("cpet_dizziness"))
    syncope = bool(ui.get("cpet_syncope"))
    palpit = bool(ui.get("cpet_palpitations"))
    arrh = bool(ui.get("cpet_arrhythmia"))
    arrh_text = _s(ui.get("cpet_arrhythmia_text"))
    st_change = _s(ui.get("cpet_st_changes")).lower()

    followups: List[str] = []
    flags: Dict[str, Any] = {}

    # BP response heuristics (keep simple and robust)
    severe_htn = (bp_dia_peak is not None and bp_dia_peak >= 110) or (bp_sys_peak is not None and bp_sys_peak >= 210)
    moderate_htn = (bp_dia_peak is not None and bp_dia_peak >= 100) or (bp_sys_peak is not None and bp_sys_peak >= 190)

    hypotension = False
    if bp_sys_rest is not None and bp_sys_peak is not None:
        if bp_sys_peak < (bp_sys_rest - 10):
            hypotension = True
    if syncope:
        hypotension = True

    ischemia = False
    if angina:
        ischemia = True
    if "depress" in st_change or "senk" in st_change:
        ischemia = True
    if "elev" in st_change or "heb" in st_change:
        ischemia = True

    parts: List[str] = []
    if bp_sys_rest is not None and bp_dia_rest is not None:
        parts.append(f"RR Ruhe {_fmt(bp_sys_rest,0)}/{_fmt(bp_dia_rest,0)} mmHg.")
    if bp_sys_peak is not None and bp_dia_peak is not None:
        parts.append(f"RR Peak {_fmt(bp_sys_peak,0)}/{_fmt(bp_dia_peak,0)} mmHg.")
    if severe_htn:
        parts.append("Hypertensive Reaktion ist ausgeprägt (insb. diastolisch).")
    elif moderate_htn:
        parts.append("Hypertensive Reaktion möglich.")
    if hypotension:
        parts.append("Hypotonie/Präsynkope Hinweis. Sicherheitslimitation möglich.")
    if arrh:
        parts.append("Arrhythmie dokumentiert." + (f" ({arrh_text})" if arrh_text else ""))
    if ischemia:
        parts.append("Ischämieverdacht (Angina/ST Veränderungen).")
    if dizziness:
        parts.append("Schwindel/Präsynkope dokumentiert.")
    if syncope:
        parts.append("Synkope dokumentiert.")
    if palpit:
        parts.append("Palpitationen dokumentiert.")
    if st_change and st_change not in ("", "keine", "none"):
        parts.append(f"EKG ST/T: {st_change}.")

    if severe_htn:
        followups.append("Bei diastolischer RR Spitze ≥110 mmHg: Messbedingungen prüfen und Hypertoniemanagement planen.")
    if hypotension:
        followups.append("Hypotonie/Präsynkope: Test als sicherheitslimitiert dokumentieren und kardiale Ursachen (LVOT, Ischämie, Rhythmus) abklären.")
    if arrh:
        followups.append("Arrhythmie: Art/Last dokumentieren, ggf. Holter und Rhythmusdiagnostik.")
    if ischemia:
        followups.append("Ischämieverdacht: zeitnahe kardiologische Abklärung (Belastungs EKG Auswertung, Bildgebung) erwägen.")

    flags["cpet_severe_htn_local"] = severe_htn
    flags["cpet_moderate_htn_local"] = moderate_htn
    flags["cpet_hypotension_local"] = hypotension
    flags["cpet_arrhythmia_local"] = arrh
    flags["cpet_ischemia_suspected_local"] = ischemia

    severity = "info"
    status = "ok"
    if ischemia or arrh or hypotension:
        severity = "bad"
        status = "safety_red_flags"
    elif severe_htn:
        severity = "warn"
        status = "hypertensive_response"
    elif moderate_htn:
        severity = "warn"
        status = "bp_attention"

    teaching = (
        "CPET ist auch ein Sicherheitstest. Blutdruck und Rhythmusantwort müssen immer dokumentiert werden. "
        "Eine ausgeprägte diastolische Hypertonie kann die Nachlast massiv erhöhen (Afterload Mismatch) und sollte therapeutisch adressiert werden. "
        "Hypotonie, Synkope, relevante Arrhythmien oder Ischämiezeichen machen den Test sicherheitslimitiert und erfordern eine unmittelbare klinische Einordnung."
    )

    return ModuleResult(
        title="Modul 7: Sicherheit (RR Antwort, Rhythmus, Ischämie)",
        status=status,
        severity=severity,
        feedback=" ".join([p for p in parts if p]).strip(),
        teaching=teaching,
        followups=followups,
        flags=flags,
    )


def analyze_module_2(ui: Dict[str, Any]) -> ModuleResult:
    vo2 = _sfk(ui, "cpet_peak_vo2_ml_kg_min")
    followups: List[str] = []
    flags: Dict[str, Any] = {}

    risk_band = None
    if vo2 is not None:
        if vo2 > 15:
            risk_band = "low"
        elif vo2 >= 11:
            risk_band = "intermediate"
        else:
            risk_band = "high"

    flags["cpet_vo2_risk_band_local"] = risk_band

    if vo2 is None:
        feedback = "V'O2max/kg nicht angegeben. Prognostische Einordnung ist nicht möglich."
        severity = "warn"
        status = "missing"
    else:
        band_txt = ""
        if risk_band == "low":
            band_txt = "Low Risk Bereich nach ESC PH 2022."
            severity = "info"
        elif risk_band == "intermediate":
            band_txt = "Intermediate Risk Bereich nach ESC PH 2022."
            severity = "warn"
        else:
            band_txt = "High Risk Bereich nach ESC PH 2022."
            severity = "bad"
        feedback = f"V'O2max/kg { _fmt(vo2,1) } mL/min/kg. {band_txt}"
        status = risk_band

    teaching = (
        "Die V'O2peak basiert auf dem Fick Prinzip: VO2 = Herzzeitvolumen mal arteriovenöse Sauerstoffdifferenz. "
        "Da die Sauerstoffausschöpfung bei vielen Patientinnen und Patienten relativ konstant ist, spiegelt V'O2peak häufig die Pumpfunktion und das Herzzeitvolumen wider. "
        "In der pulmonalen Hypertonie wird V'O2peak daher zur Risikostratifizierung verwendet."
    )

    return ModuleResult(
        title="Modul 2: Aerobe Kapazität (Prognose)",
        status=status,
        severity=severity,
        feedback=feedback,
        teaching=teaching,
        followups=followups,
        flags=flags,
    )


def analyze_module_3(ui: Dict[str, Any]) -> ModuleResult:
    o2_pulse_ml = _sfk(ui, "cpet_peak_o2_pulse_ml")
    o2_pattern = _s(ui.get("cpet_o2_pulse_pattern")).lower() or "unbekannt"
    o2_slope = _sfk(ui, "cpet_o2_pulse_slope")
    bp_sys = _sfk(ui, "cpet_bp_sys_peak")
    bp_dia = _sfk(ui, "cpet_bp_dia_peak")
    followups: List[str] = []
    flags: Dict[str, Any] = {}

    plateau = o2_pattern in ("plateau", "fallend")
    afterload = (bp_dia is not None and bp_dia >= 100)
    afterload_mismatch = bool(plateau and afterload)

    flags["cpet_o2_pulse_plateau"] = plateau
    flags["cpet_afterload_mismatch"] = afterload_mismatch

    parts: List[str] = []
    if o2_pulse_ml is not None:
        parts.append(f"O2 Puls Peak { _fmt(o2_pulse_ml,1) } mL.")
    if o2_slope is not None:
        parts.append(f"O2 Puls Slope { _fmt(o2_slope,2) }.")
    if o2_pattern and o2_pattern != "unbekannt":
        parts.append(f"O2 Puls Verlauf: {o2_pattern}.")
    if bp_sys is not None or bp_dia is not None:
        bp_txt = f"{_fmt(bp_sys,0)}/{_fmt(bp_dia,0)} mmHg" if (bp_sys is not None and bp_dia is not None) else ""
        if bp_txt:
            parts.append(f"Blutdruck Peak {bp_txt}.")

    if plateau:
        parts.append("Ein Plateau des O2 Puls spricht für eine limitierte Schlagvolumensteigerung unter Belastung.")
    if afterload:
        parts.append("Die diastolische Nachlast ist deutlich erhöht.")
    if afterload_mismatch:
        parts.append("Kombination aus O2 Puls Plateau und hoher diastolischer Nachlast passt zu Afterload Mismatch.")
        followups.append("Bitte Hypertonie Therapie und Messbedingungen prüfen."
                        )

    if afterload_mismatch:
        severity = "warn"
        status = "afterload_mismatch"
    elif plateau:
        severity = "warn"
        status = "stroke_volume_limited"
    else:
        severity = "info"
        status = "ok"

    teaching = (
        "Der O2 Puls ist VO2 geteilt durch Herzfrequenz und dient als Surrogat für das Schlagvolumen, wenn die Sauerstoffausschöpfung stabil ist. "
        "Unter Belastung sollte der O2 Puls typischerweise ansteigen. Ein Plateau oder Abfall spricht dafür, dass das Schlagvolumen nicht weiter gesteigert werden kann. "
        "Wenn gleichzeitig die diastolische Blutdrucklast stark erhöht ist, kann die Pumpfunktion sekundär durch Nachlast limitiert sein."
    )

    return ModuleResult(
        title="Modul 3: Zirkulation (Pumpe und Nachlast)",
        status=status,
        severity=severity,
        feedback=" ".join([p for p in parts if p]).strip(),
        teaching=teaching,
        followups=followups,
        flags=flags,
    )


def analyze_module_4(ui: Dict[str, Any]) -> ModuleResult:
    vevco2 = _sfk(ui, "cpet_ve_vco2_slope")
    pet_rest = _sfk(ui, "cpet_petco2_rest_mmhg")
    pet_peak = _sfk(ui, "cpet_petco2_peak_mmhg")
    pet_vt1 = _sfk(ui, "cpet_petco2_vt1_mmhg")
    br = _sfk(ui, "cpet_breathing_reserve_pct")
    followups: List[str] = []
    flags: Dict[str, Any] = {}

    # Determine PETCO2 trend
    pet_start = pet_rest if pet_rest is not None else pet_vt1
    pet_end = pet_peak
    pet_falls = None
    if pet_start is not None and pet_end is not None:
        pet_falls = (pet_end < (pet_start - 2))

    ve_high = (vevco2 is not None and vevco2 >= 35)
    pet_low = (pet_start is not None and pet_start < 30)
    mech_ok = (br is not None and br >= 20)  # high reserve suggests no mechanical limitation

    pulm_vasc_pattern = bool(ve_high and pet_low and (pet_falls is True) and (br is None or mech_ok))
    flags["cpet_pulm_vasc_pattern"] = pulm_vasc_pattern

    parts: List[str] = []
    if vevco2 is not None:
        parts.append(f"V'E/V'CO2 Slope { _fmt(vevco2,2) }.")
        if ve_high:
            parts.append("Ventilatorische Effizienz ist deutlich eingeschränkt, Totraumanteil wahrscheinlich erhöht.")
    if pet_start is not None:
        parts.append(f"PETCO2 früh { _fmt(pet_start,0) } mmHg.")
        if pet_low:
            parts.append("PETCO2 ist niedrig, das passt zu ventilierter aber schlecht perfundierter Lunge.")
    if pet_end is not None:
        parts.append(f"PETCO2 Peak { _fmt(pet_end,0) } mmHg.")
        if pet_falls is True:
            parts.append("PETCO2 fällt unter Belastung.")
    if br is not None:
        parts.append(f"Atemreserve { _fmt(br,0) } %.")
        if br < 15:
            parts.append("Atemreserve ist niedrig, ventilatorische Limitation ist möglich.")
    if pulm_vasc_pattern:
        parts.append("Kombination aus hohem Slope, niedrigem und fallendem PETCO2 bei erhaltener Atemreserve passt zu pulmonal vaskulärem Muster, Verdacht auf PH.")
        followups.append("Empfehlung: Korrelation mit RHK, Echo und Bildgebung."
                        )

    if pulm_vasc_pattern:
        severity = "bad"
        status = "pulmonary_vascular_pattern"
    elif ve_high:
        severity = "warn"
        status = "ventilatory_inefficiency"
    else:
        severity = "info"
        status = "ok"

    teaching = (
        "Die V'E/V'CO2 Slope beschreibt, wie viel Ventilation benötigt wird, um CO2 abzuatmen. Normwerte liegen typischerweise unter 30. "
        "Erhöhte Werte sprechen für Ineffizienz und oft für erhöhten Totraum, etwa bei eingeschränkter Perfusion. "
        "PETCO2 ist ein Marker des alveolären CO2 und reflektiert die Perfusion. In pulmonal vaskulären Erkrankungen ist PETCO2 häufig in Ruhe niedrig und kann unter Belastung weiter abfallen. "
        "Wenn die Atemreserve erhalten ist, spricht dies gegen eine primär mechanische ventilatorische Limitation und lenkt die Diagnose in Richtung Gefäße."
    )

    return ModuleResult(
        title="Modul 4: Ventilation und Gasaustausch (Guazzi Core)",
        status=status,
        severity=severity,
        feedback=" ".join([p for p in parts if p]).strip(),
        teaching=teaching,
        followups=followups,
        flags=flags,
    )


def analyze_module_9panel(ui: Dict[str, Any]) -> ModuleResult:
    """Interpretation helper for the Wasserman-style 9-panel plot.

    We deliberately ask for *pattern* decisions rather than raw curves, because
    the plot is often reviewed visually and values are not always exported.
    The module is optional and should never block the workflow.
    """

    available = bool(ui.get("cpet_9panel_available"))
    vt1 = _s(ui.get("cpet_9panel_vt1_identified")).lower()  # ja / nein / unklar
    vt1_method = _s(ui.get("cpet_9panel_vt1_method"))
    rcp = _s(ui.get("cpet_9panel_rcp_identified")).lower()  # ja / nein / unklar
    eov = bool(ui.get("cpet_9panel_eov"))
    flow_lim = _s(ui.get("cpet_9panel_flowvol_limit")).lower()  # ja / nein / unklar
    vo2wr_pattern = _s(ui.get("cpet_9panel_vo2wr_pattern")).lower()  # linear / flach / plateau / unklar
    veeq_pattern = _s(ui.get("cpet_9panel_veeq_pattern")).lower()  # normal / frueh / kein / unklar
    comment = _s(ui.get("cpet_9panel_comment"))

    # Existing numeric values (optional) to enrich teaching
    vo2wr = _sfk(ui, "cpet_vo2_wr_slope_ml_min_w")
    spo2_nadir = _sfk(ui, "cpet_spo2_nadir_pct")
    br = _sfk(ui, "cpet_breathing_reserve_pct")
    pet_rest = _sfk(ui, "cpet_petco2_rest_mmhg")
    pet_peak = _sfk(ui, "cpet_petco2_peak_mmhg")
    vevco2 = _sfk(ui, "cpet_ve_vco2_slope")

    followups: List[str] = []
    flags: Dict[str, Any] = {
        "cpet_9panel_available": available,
        "cpet_eov_present": eov,
        "cpet_flowvol_limit_visual": (flow_lim == "ja"),
    }

    if not available:
        feedback = "9 Felder Grafik nicht dokumentiert. Optional empfohlen, da sie die CPET Muster schnell verständlich macht."
        teaching = (
            "Die 9 Felder Grafik nach Wasserman fasst die wichtigsten Zusammenhänge in einer Ansicht zusammen, z.B. V'O2 Verlauf, Ventilation, "
            "Ventilatorische Äquivalente, PETCO2, O2 Puls, Herzfrequenz und Sättigung. "
            "Damit lassen sich Muster wie ventilatorische Limitation, zirkulatorische Limitation, Deconditioning oder pulmonal vaskuläre Limitation "
            "schneller erkennen und vermitteln."
        )
        return ModuleResult(
            title="Modul 5: 9 Felder Grafik (Wasserman)",
            status="missing",
            severity="info",
            feedback=feedback,
            teaching=teaching,
            followups=[],
            flags=flags,
        )

    parts: List[str] = []

    # VT1 / RCP checks
    if vt1:
        if vt1.startswith("ja"):
            if vt1_method:
                parts.append(f"VT1 identifiziert ({vt1_method}).")
            else:
                parts.append("VT1 identifiziert.")
        elif vt1.startswith("nein"):
            parts.append("VT1 nicht sicher identifiziert.")
            followups.append("VT1 möglichst über V Slope oder Ventilatorische Äquivalente prüfen, da sie die Musterinterpretation stabilisiert.")
        else:
            parts.append("VT1 unklar.")

    if rcp:
        if rcp.startswith("ja"):
            parts.append("RCP identifiziert.")
        elif rcp.startswith("nein"):
            parts.append("RCP nicht identifiziert.")
        else:
            parts.append("RCP unklar.")

    # VO2 Work relation (curve pattern + optional numeric slope)
    if vo2wr_pattern and vo2wr_pattern != "":
        if vo2wr_pattern in ("plateau", "flach"):
            parts.append("V'O2 zu Leistung: flacher Verlauf oder Plateau.")
        elif vo2wr_pattern == "linear":
            parts.append("V'O2 zu Leistung: linearer Verlauf.")
        else:
            parts.append("V'O2 zu Leistung: unklar.")

    if vo2wr is not None:
        parts.append(f"VO2Ws {_fmt(vo2wr,2)} mL/min/W.")
        if vo2wr < 8:
            parts.append("VO2Ws ist niedrig und passt zu zirkulatorischer Limitation oder peripherer Einschränkung.")

    # Ventilatory equivalents curve
    if veeq_pattern:
        if veeq_pattern.startswith("fr"):
            parts.append("Ventilatorische Äquivalente steigen früh an.")
        elif veeq_pattern.startswith("kein"):
            parts.append("Kein klarer Knick in den Ventilatorischen Äquivalenten.")
        elif veeq_pattern.startswith("normal"):
            parts.append("Typischer Knick der Ventilatorischen Äquivalente.")
        elif veeq_pattern.startswith("unk"):
            parts.append("Ventilatorische Äquivalente unklar.")

    # EOV and ventilatory limitation
    if eov:
        parts.append("Exercise oscillatory ventilation dokumentiert.")
        followups.append("EOV ist prognostisch relevant und wird bei Herzinsuffizienz und pulmonal vaskulären Erkrankungen beobachtet.")

    if flow_lim:
        if flow_lim == "ja":
            parts.append("Flow Volume Loop Einschränkung spricht für ventilatorische Limitation.")
        elif flow_lim == "unklar":
            parts.append("Flow Volume Loop Einschränkung unklar.")

    # Enrich with numeric hints already collected elsewhere
    if spo2_nadir is not None and spo2_nadir < 90:
        parts.append(f"Desaturation: SpO2 Nadir {_fmt(spo2_nadir,0)} %.")
    if br is not None and br < 15:
        parts.append("Atemreserve ist niedrig, ventilatorische Limitation möglich.")
    if vevco2 is not None and vevco2 >= 35:
        parts.append("Ventilatorische Effizienz eingeschränkt (hoher V'E/V'CO2 Slope).")
    if pet_rest is not None and pet_peak is not None and (pet_peak < pet_rest - 2):
        parts.append("PETCO2 fällt unter Belastung, vaskuläres Muster möglich.")

    if comment:
        parts.append("Kommentar: " + comment)

    # Severity heuristic
    severity = "info"
    status = "ok"
    if eov:
        severity = "warn"
        status = "eov"
    if vo2wr_pattern in ("plateau", "flach"):
        severity = "warn" if severity != "bad" else severity
        status = "abnormal_curve"
    if (flow_lim == "ja"):
        severity = "warn" if severity != "bad" else severity
        status = "vent_limit"

    teaching = (
        "Die 9 Felder Grafik nach Wasserman hilft, Kurvenmuster in Beziehung zu setzen. "
        "Wichtig sind insbesondere: V'O2 zu Leistung (VO2Ws), O2 Puls Verlauf, Herzfrequenzantwort, Ventilatorische Äquivalente (V'E/V'O2 und V'E/V'CO2), "
        "PETCO2 Verlauf und SpO2. "
        "Pulmonal vaskuläre Muster zeigen oft hohe V'E/V'CO2, niedrige PETCO2 Werte mit Abfall unter Belastung und erhaltene Atemreserve. "
        "Ventilatorische Limitation zeigt sich typischerweise durch niedrige Atemreserve und eine relevante Annäherung der Atemschleife an die Flow Volume Grenze. "
        "Exercise oscillatory ventilation ist ein oszillierendes Ventilationsmuster und gilt als prognostisch ungünstig." 
    )

    return ModuleResult(
        title="Modul 5: 9 Felder Grafik (Wasserman)",
        status=status,
        severity=severity,
        feedback=" ".join([p for p in parts if p]).strip(),
        teaching=teaching,
        followups=followups,
        flags=flags,
    )


def analyze_module_final(ui: Dict[str, Any], m0: ModuleResult, m1: ModuleResult, m2: ModuleResult, m3: ModuleResult, m4: ModuleResult, m5: ModuleResult, m6: ModuleResult, m7: ModuleResult, m9: ModuleResult) -> ModuleResult:
    """Final classification and guideline-aligned next steps.

    Produces a single, clinician-facing statement that is consistent with the
    upstream modules and explicitly documents uncertainty.
    """

    followups: List[str] = []
    flags: Dict[str, Any] = {}

    # Optional manual override by the physician
    override = _s(ui.get("cpet_limitation_override")).lower().strip()
    override_txt = _s(ui.get("cpet_limitation_override_text")).strip()
    next_steps_manual = _s(ui.get("cpet_next_steps_manual")).strip()

    # Heuristic classification (deterministic)
    label = "nicht beurteilbar"
    confidence = "niedrig"

    # Safety first
    if m7.status == "safety_red_flags" or bool(m0.flags.get("cpet_stop_safety_local")):
        label = "sicherheitslimitiert"
        confidence = "hoch"
    elif bool(m5.flags.get("cpet_mechanical_limited_local")):
        label = "pulmonal mechanisch limitiert"
        confidence = "mittel"
    elif m4.status == "pulmonary_vascular_pattern":
        label = "pulmonal vaskuläres Muster (PH verdächtig)"
        confidence = "hoch"
    else:
        # Cardiac vs peripheral / deconditioning
        vo2 = _sfk(ui, "cpet_peak_vo2_ml_kg_min")
        vevco2 = _sfk(ui, "cpet_ve_vco2_slope")
        br = _sfk(ui, "cpet_breathing_reserve_pct")
        o2_plateau = bool(m3.flags.get("cpet_o2_pulse_plateau"))
        chrono = bool(m1.flags.get("cpet_chronotropic_suspected"))

        # deconditioning: low VO2 with otherwise normal ventilatory efficiency and no mechanical limitation
        if vo2 is not None and vo2 < 15 and (vevco2 is not None and vevco2 < 34) and (br is None or br >= 20) and (not o2_plateau) and (not chrono) and (not bool(m6.flags.get("cpet_desaturation_local"))):
            label = "peripher/deconditioning wahrscheinlich"
            confidence = "mittel"
        elif o2_plateau or chrono:
            label = "zirkulatorisch limitiert (kardiale Komponente wahrscheinlich)"
            confidence = "mittel"
        else:
            label = "gemischt oder unklar"
            confidence = "niedrig"

    # Manual override takes precedence but must be documented
    if override:
        label = f"{label} (ärztlich überschrieben: {override})"
        confidence = "hoch"  # physician decision
        if not override_txt:
            followups.append("Bei ärztlichem Override bitte kurz die Begründung dokumentieren.")

    flags["cpet_limitation_type_local"] = label
    flags["cpet_limitation_confidence_local"] = confidence

    # Guideline aligned next steps (doctor-facing, deterministic)
    rec: List[str] = []

    if "pulmonal vaskul" in label or m4.status == "pulmonary_vascular_pattern":
        rec.append("Korrelation mit Echo und RHK. Bei Verdacht auf CTEPH: V/Q oder CT Angio erwägen.")
        rec.append("Kontext prüfen: Atemreserve erhalten, hoher V'E/V'CO2 und fallendes PETCO2 sprechen für vaskuläre Limitation.")
    if "mechanisch" in label:
        rec.append("Mechanische Limitation belegt über niedrige Atemreserve/V'E/MVV. Lufu und ggf. Bildgebung/Obstruktionstherapie prüfen.")
    if "zirkulatorisch" in label:
        rec.append("Zirkulatorische Limitation: O2 Puls Verlauf, VO2Ws und Blutdruckantwort mit Echo/RHK kontextualisieren.")
        if m1.status == "chronotropic_incompetence":
            rec.append("Chronotrope Inkompetenz: Medikation (Betablocker) prüfen, Rhythmusdiagnostik (Holter) erwägen.")
    if bool(m6.flags.get("cpet_desaturation_local")):
        rec.append("Relevante Desaturation: Differenzialdiagnostik (Diffusion/ILD, Shunt, V/Q Mismatch, PH) und O2 Setting dokumentieren.")
    if bool(m7.flags.get("cpet_severe_htn_local")):
        rec.append("Ausgeprägte hypertensive Antwort: Nachlast berücksichtigen (Afterload Mismatch), Hypertoniemanagement planen.")
    if bool(m7.flags.get("cpet_arrhythmia_local")) or bool(m7.flags.get("cpet_ischemia_suspected_local")):
        rec.append("Sicherheitsbefund: Arrhythmie/Ischämiezeichen → zeitnahe Abklärung und Dokumentation als sicherheitslimitiert.")

    if m0.status == "submaximal":
        rec.append("Testqualität limitiert: Aussagen zu VO2peak nur eingeschränkt. Abbruchgrund und Anstrengung explizit dokumentieren.")

    feedback_parts: List[str] = []
    feedback_parts.append(f"Limitationstyp: {label} (Konfidenz: {confidence}).")
    if override and override_txt:
        feedback_parts.append(f"Begründung Override: {override_txt}.")
    if next_steps_manual:
        feedback_parts.append(f"Zusätzliche ärztliche Planung: {next_steps_manual}.")
    if rec:
        feedback_parts.append("Next Steps: " + " ".join(rec))

    if next_steps_manual:
        feedback_parts.append("Zusatz (ärztlich): " + next_steps_manual)

    teaching = (
        "Ein CPET Befund sollte immer einen Limitationstyp enthalten (kardial, pulmonal mechanisch, pulmonal vaskulär, peripher/deconditioning, gemischt oder nicht beurteilbar). "
        "Diese Einordnung ist nur dann belastbar, wenn Testqualität, Sicherheitsaspekte und die Kernelemente (VO2peak, VE/VCO2, PETCO2, Atemreserve, O2 Puls, Blutdruck und SpO2) gemeinsam bewertet werden. "
        "Das Ziel ist ein widerspruchsfreier, leitliniennaher Befund mit klaren nächsten diagnostischen Schritten."
    )

    severity = "info" if confidence in ("mittel", "hoch") else "warn"
    if "sicherheits" in label or "PH" in label:
        severity = "bad" if "PH" in label else "warn"

    return ModuleResult(
        title="Modul 8: Limitationstyp und Next Steps",
        status="final",
        severity=severity,
        feedback=" ".join([p for p in feedback_parts if p]).strip(),
        teaching=teaching,
        followups=followups,
        flags=flags,
    )


def _headline_from_modules(m0: ModuleResult, m2: ModuleResult, m4: ModuleResult, m5: ModuleResult, m6: ModuleResult, mfinal: ModuleResult) -> str:
    """One-line headline suitable for letterhead."""
    # Prefer explicit final label when available
    label = (mfinal.flags.get("cpet_limitation_type_local") or "").strip()
    if not label:
        label = (mfinal.feedback or "").strip()
    qual = (m0.flags.get("cpet_test_quality_status") or "").strip()
    qual_prefix = ""
    if qual in ("eher submaximal", "unklar"):
        qual_prefix = "eingeschränkt beurteilbar – "
    if "pulmonal vaskul" in label or m4.status == "pulmonary_vascular_pattern":
        return f"CPET: {qual_prefix}pulmonal-vaskuläres Muster (PH-Verdacht)"
    if "pulmonal mechan" in label or bool(m5.flags.get("cpet_mechanical_limited_local")):
        return f"CPET: {qual_prefix}ventilatorische Limitation wahrscheinlich"
    if "sicherheits" in label:
        return "CPET: sicherheitslimitiert"
    # VO2 risk as fallback if nothing else stands out
    if m2.status in ("low", "intermediate", "high"):
        return f"CPET: {qual_prefix}aerobe Kapazität {m2.status} (ESC PH 2022)"
    return f"CPET: {qual_prefix}kein eindeutiges Limitationstyp-Muster"


def _clinical_summary_from_modules(ui: Dict[str, Any], m0: ModuleResult, m1: ModuleResult, m2: ModuleResult, m3: ModuleResult, m4: ModuleResult, m5: ModuleResult, m6: ModuleResult, m7: ModuleResult, m9: ModuleResult, mfinal: ModuleResult) -> str:
    """Clinician-facing CPET interpretation (compact, actionable)."""
    lines: List[str] = []

    # 1) Test quality
    qual = (m0.flags.get("cpet_test_quality_status") or "").strip()
    stop = _s(ui.get("cpet_stop_reason")).strip()
    if stop:
        lines.append(f"Testende: {stop}.")
    if qual:
        lines.append(f"Testqualität: {qual}.")

    # 2) Key prognostic axis
    vo2 = _sfk(ui, "cpet_peak_vo2_ml_kg_min")
    if vo2 is not None:
        # ESC thresholds are already encoded in module2.status
        if m2.status in ("low", "intermediate", "high"):
            lines.append(f"Aerobe Kapazität: V'O2max/kg {vo2:.1f} mL/min/kg ({m2.status} nach ESC PH 2022).")
        else:
            lines.append(f"Aerobe Kapazität: V'O2max/kg {vo2:.1f} mL/min/kg.")

    # 3) Dominant pattern(s)
    if bool(m1.flags.get("cpet_chronotropic_suspected")):
        hr_pct = _sfk(ui, "cpet_hr_pct_pred")
        if hr_pct is not None:
            lines.append(f"Antrieb: Diskrepanz zwischen metabolischer Ausbelastung und HF-Anstieg (chronotrope Inkompetenz möglich; HF {hr_pct:.0f}% Soll).")
        else:
            lines.append("Antrieb: Muster vereinbar mit chronotroper Inkompetenz (bei metabolischer Ausbelastung).")

    if m3.status == "afterload_mismatch":
        bp_dia = _sfk(ui, "cpet_bp_dia_peak")
        if bp_dia is not None:
            lines.append(f"Zirkulation: O2-Puls-Plateau bei deutlich erhöhter diastolischer Belastung (RR diast {bp_dia:.0f} mmHg) – Afterload-Mismatch wahrscheinlich.")
        else:
            lines.append("Zirkulation: O2-Puls-Plateau – Afterload-Mismatch möglich (Nachlast prüfen).")

    if m4.status == "pulmonary_vascular_pattern":
        vevco2 = _sfk(ui, "cpet_ve_vco2_slope")
        pet_rest = _sfk(ui, "cpet_petco2_rest_mmhg")
        pet_peak = _sfk(ui, "cpet_petco2_peak_mmhg")
        bits = []
        if vevco2 is not None:
            bits.append(f"V'E/V'CO2 Slope {vevco2:.0f}")
        if pet_rest is not None and pet_peak is not None:
            bits.append(f"PETCO2 {pet_rest:.0f}→{pet_peak:.0f} mmHg")
        if bits:
            lines.append("Ventilation/Gasaustausch: " + ", ".join(bits) + " – pulmonal-vaskuläres Belastungsmuster (PH verdächtig).")
        else:
            lines.append("Ventilation/Gasaustausch: Muster vereinbar mit pulmonal-vaskulärer Limitation (PH verdächtig).")

    if bool(m5.flags.get("cpet_mechanical_limited_local")):
        ve_mvv = m5.flags.get("cpet_ve_mvv_ratio_local")
        if ve_mvv is not None:
            lines.append(f"Mechanik: V'E/MVV {ve_mvv:.2f} – ventilatorische Reserve eingeschränkt (mechanische Limitation möglich).")
        else:
            lines.append("Mechanik: Niedrige ventilatorische Reserve spricht für mechanische Limitation (Lunge/Obstruktion/Dynamik).")

    if bool(m6.flags.get("cpet_desaturation_local")):
        spo2_nadir = _sfk(ui, "cpet_spo2_nadir_pct")
        if spo2_nadir is not None:
            lines.append(f"Gasaustausch: Relevante Desaturation (SpO2 Nadir {spo2_nadir:.0f}%).")

    # 4) Safety summary (only if present)
    if bool(ui.get("cpet_angina")):
        lines.append("Sicherheit: Angina unter Belastung dokumentiert.")
    if bool(ui.get("cpet_syncope")):
        lines.append("Sicherheit: Synkope/Präsynkope unter Belastung dokumentiert.")
    if bool(ui.get("cpet_arrhythmia")):
        txt = _s(ui.get("cpet_arrhythmia_text")).strip()
        lines.append("Sicherheit: Arrhythmie unter Belastung" + (f" ({txt})." if txt else "."))

    # 5) Final classification & next steps (compact)
    lim = (mfinal.flags.get("cpet_limitation_type_local") or "").strip()
    conf = (mfinal.flags.get("cpet_limitation_confidence_local") or "").strip()
    if lim:
        lines.append(f"Gesamteinschätzung: {lim} (Konfidenz: {conf or 'unklar'}).")
    # next steps: keep short, already deterministic in mfinal.feedback after 'Next Steps:'
    fb = (mfinal.feedback or "")
    if "Next Steps:" in fb:
        ns = fb.split("Next Steps:", 1)[1].strip()
        if ns:
            lines.append("Empfehlungen: " + ns)

    return " ".join([x for x in lines if x]).strip()


def analyze(ui: Dict[str, Any]) -> Optional[SpiroLogicResult]:
    if not bool(ui.get("cpet_done")):
        return None

    m0 = analyze_module_0_quality(ui)
    m1 = analyze_module_1(ui)
    m2 = analyze_module_2(ui)
    m3 = analyze_module_3(ui)
    m4 = analyze_module_4(ui)
    m5 = analyze_module_5_mech(ui)
    m6 = analyze_module_6_gas(ui)
    m7 = analyze_module_7_safety(ui)
    m9 = analyze_module_9panel(ui)
    mfinal = analyze_module_final(ui, m0, m1, m2, m3, m4, m5, m6, m7, m9)

    # Derived flags for rule engine / downstream usage
    derived: Dict[str, Any] = {
        **m0.flags,
        **m1.flags,
        **m2.flags,
        **m3.flags,
        **m4.flags,
        **m5.flags,
        **m6.flags,
        **m7.flags,
        **m9.flags,
        **mfinal.flags,
    }

    # Overall summary (short)
    bullets: List[str] = []
    if m7.status == "safety_red_flags":
        bullets.append("Sicherheits Red Flags (RR/Rhythmus/Ischämie) dokumentiert.")
    if m0.status == "submaximal":
        bullets.append("Testqualität limitiert (submaximal).")
    if m1.status == "chronotropic_incompetence":
        bullets.append("Chronotrope Inkompetenz wahrscheinlich.")
    if m2.status in ("low", "intermediate", "high"):
        bullets.append(f"V'O2 Risiko: {m2.status}.")
    if m3.status == "afterload_mismatch":
        bullets.append("Afterload Mismatch möglich.")
    if m4.status == "pulmonary_vascular_pattern":
        bullets.append("Pulmonal vaskuläres CPET Muster, Verdacht auf PH.")
    if bool(m6.flags.get("cpet_desaturation_local")):
        bullets.append("Relevante Desaturation.")
    if bool(m5.flags.get("cpet_mechanical_limited_local")):
        bullets.append("Mechanische ventilatorische Limitation möglich.")
    if bool(m9.flags.get("cpet_eov_present")):
        bullets.append("EOV dokumentiert.")
    if not bullets:
        bullets.append("Keine eindeutige pathologische Mustererkennung anhand der eingegebenen CPET Werte.")

    overall_summary = " ".join(bullets)

    # Report text (professional interpretation)
    report_lines: List[str] = []
    report_lines.append("Spiroergometrie/CPET – strukturierte Beurteilung (Spiro-Logic).")
    if m0.feedback:
        report_lines.append("Testqualität: " + m0.feedback)
    if m1.feedback:
        report_lines.append("Antrieb: " + m1.feedback)
    if m2.feedback:
        report_lines.append("Aerobe Kapazität: " + m2.feedback)
    if m3.feedback:
        report_lines.append("Zirkulation: " + m3.feedback)
    if m4.feedback:
        report_lines.append("Ventilation und Gasaustausch: " + m4.feedback)
    if m5.feedback:
        report_lines.append("Mechanik: " + m5.feedback)
    if m6.feedback:
        report_lines.append("SpO2/O2: " + m6.feedback)
    if m7.feedback:
        report_lines.append("Sicherheit: " + m7.feedback)
    if bool(m9.flags.get("cpet_9panel_available")) and m9.feedback:
        report_lines.append("9 Felder Grafik: " + m9.feedback)

    if mfinal.feedback:
        report_lines.append("Limitation/Next Steps: " + mfinal.feedback)

    report_text = "\n".join(report_lines).strip()

    # Clinician-facing summary and one-line headline (avoid dumping raw zeros)
    headline = _headline_from_modules(m0, m2, m4, m5, m6, mfinal)
    clinical_summary = _clinical_summary_from_modules(ui, m0, m1, m2, m3, m4, m5, m6, m7, m9, mfinal)

    return SpiroLogicResult(
        module0=m0,
        module1=m1,
        module2=m2,
        module3=m3,
        module4=m4,
        module5_mech=m5,
        module6_gas=m6,
        module7_safety=m7,
        module9=m9,
        module_final=mfinal,
        overall_summary=overall_summary,
        headline=headline,
        clinical_summary=clinical_summary,
        report_text=report_text,
        derived=derived,
    )


def render_module_html(m: ModuleResult) -> str:
    badge = _badge(m.severity)
    fb = m.feedback.strip()
    teach = m.teaching.strip()
    fu = m.followups or []
    fu_html = "".join([f"<li>{_escape(x)}</li>" for x in fu])
    fu_block = f"<div class='spiro-edu__follow'><div class='spiro-edu__sub'>Nachfragen</div><ul>{fu_html}</ul></div>" if fu else ""
    return (
        f"<div class='spiro-edu'>"
        f"<div class='spiro-edu__title'>{badge} { _escape(m.title) }</div>"
        f"<div class='spiro-edu__feedback'>{_escape(fb) if fb else ''}</div>"
        f"<div class='spiro-edu__sub'>Physiologie</div>"
        f"<div class='spiro-edu__teach'>{_escape(teach)}</div>"
        f"{fu_block}"
        f"</div>"
    )


def render_overall_html(res: SpiroLogicResult) -> str:
    tech = _escape(res.report_text).replace(chr(10), '<br>')
    clinical = _escape(res.clinical_summary).replace(chr(10), '<br>')
    headline = _escape(res.headline)
    return (
        "<div class='spiro-edu spiro-edu--overall'>"
        "<div class='spiro-edu__title'>Zusammenfassung</div>"
        f"<div class='spiro-edu__feedback'>{_escape(res.overall_summary)}</div>"
        "<div class='spiro-edu__sub'>Kurzheadline (für Arztbriefkopf)</div>"
        f"<div class='spiro-edu__fb'><b>{headline}</b></div>"
        "<div class='spiro-edu__sub'>Klinische Zusammenfassung</div>"
        f"<div class='spiro-edu__teach'>{clinical}</div>"
        "<details style='margin-top:10px'>"
        "<summary style='cursor:pointer; font-weight:600'>Technische Details (optional)</summary>"
        f"<div style='margin-top:8px'>{tech}</div>"
        "</details>"
        "</div>"
    )


def _escape(x: str) -> str:
    return (
        x.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def build_wizard_outputs(ui: Dict[str, Any]) -> Dict[str, Any]:
    """Return HTML blocks and derived flags for UI wiring."""
    res = analyze(ui)
    if not res:
        return {
            "mod0_html": "<div class='docx-muted'>Wizard ist erst aktiv, wenn CPET durchgeführt angehakt ist.</div>",
            "mod1_html": "<div class='docx-muted'>Wizard ist erst aktiv, wenn CPET durchgeführt angehakt ist.</div>",
            "mod2_html": "",
            "mod3_html": "",
            "mod4_html": "",
            "mod5_html": "",
            "mod6_html": "",
            "mod7_html": "",
            "mod9_html": "",
            "modfinal_html": "",
            "overall_html": "",
            "report_text": "",
            "derived": {},
            "need_chrono_followups": False,
        }
    need_chrono = bool(res.module1.status == "chronotropic_incompetence")
    return {
        "mod0_html": render_module_html(res.module0),
        "mod1_html": render_module_html(res.module1),
        "mod2_html": render_module_html(res.module2),
        "mod3_html": render_module_html(res.module3),
        "mod4_html": render_module_html(res.module4),
        "mod5_html": render_module_html(res.module5_mech),
        "mod6_html": render_module_html(res.module6_gas),
        "mod7_html": render_module_html(res.module7_safety),
        "mod9_html": render_module_html(res.module9),
        "modfinal_html": render_module_html(res.module_final),
        "overall_html": render_overall_html(res),
        "headline": res.headline,
        "clinical_summary": res.clinical_summary,
        "report_text": res.report_text,
        "derived": res.derived,
        "need_chrono_followups": need_chrono,
        "suspect_ph": bool(res.module4.status == "pulmonary_vascular_pattern"),
        "eov_present": bool(res.module9.flags.get("cpet_eov_present")),
    }